#define settings here
#config of the wanted client. only uncomment one client at a time. It will also be used as filename
#    client: iphone
#    client: android
#    client: chrome_windows
#    client: chrome_macintosh
#    client: firefox_windows
#    client: firefox_macintosh
client: linux
#config of the aws S3 parameters
s3_bucket: firstcrawlerbucket
# config of the logging
logconfig:
  version: 1
  disable_existing_loggers: true
  formatters:
    standard:
      format: " %(asctime)s: (%(filename)s): %(levelname)s: %(funcName)s Line: %(lineno)d - %(message)s"
      datefmt: '%m/%d/%Y|%I:%M:%S|%p'
    simple:
      format: '%(asctime)s %(levelname)s:%(message)s'
  handlers:
    console_handler:
      class: logging.StreamHandler
      level: WARNING
      formatter: simple

    file_handler:
      class: logging.FileHandler
      level: DEBUG
      filename: log/logging.logging
      mode: a
      formatter: standard

  root:
    handlers: [console_handler, file_handler]
    level: DEBUG
    propagate: true
