#define settings here
#could be done in a similar style like it is done in scrapy
#    client: safari
#    client: iphone
#    client: android
#    client: chrome_windows
#    client: chrome_macintosh
#    client: firefox_windows
#    client: firefox_macintosh
#    client: linux
